config/routes.rb
Netdiffness::Application.routes.draw do
  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users
  resources :scans, only: [:index, :show, :create, :new, :update]

  match 'scans/:id/rescan', to: 'scans#rescan', as: :rescan, via: [ :post ]
  match 'scan_results/:id/compare/:cid', to: 'scan_results#compare', as: :compare, via: [ :get ]
end

app/models/scan.rb
require 'securerandom'
require 'nmap/xml'

class Scan < ActiveRecord::Base
  belongs_to :user
  has_many :scan_results
  validates_format_of :targets, :with => /(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([1-2]\d|3[0-2]|\d))/i, :on => :create

  def start_scan
    scan_result = ScanResult.create(scan_id: self.id)
    SimpleScanWorker.perform_async(scan_result.uuid, self.targets)
    self.last_scan = Time.now
    self.save
  end

  def get_last_diff_scan_result
    ScanResult.where("scan_id = ? AND raw_result is NOT NULL", self.id).last
  end

  def get_history_of_scans(result_b)
    # [[0.4, 1], [3, 2], [4, 2], [5, 2], [1, 1]]
    # Change this to return an intermediate value depending on the day
    # Change this to calculate the amount of change between dates
    result = []
    ScanResult.where("scan_id = ? AND raw_result is NOT NULL", self.id).each do |r|
      result << [r.created_at.month, r.compare(result_b).count, r.id]
    end
    result
  end
end

app/models/scan_result.rb
class ScanResult < ActiveRecord::Base
  belongs_to :scan
  before_create :generate_random_uuid

  def result
    return nil unless self.raw_result
    result_hash = {}

    xml_document = StringIO.new(self.raw_result)
    Nmap::XML.new(xml_document) do |xml|
      xml.each_host do |host|
        result_hash[host.address] = []
        host.each_port do |port|
          result_hash[host.address] << "#{port.number}/#{port.protocol}" if port.state == :open
        end
      end
    end
    result_hash
  end

  def compare(scan_result)
    HashDiff.diff(self.result, scan_result.result, :delimiter => ';')
  end

  private
  def generate_random_uuid
    self.uuid = SecureRandom.uuid()
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :scans
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    redirect_to controller: "scans", action: "index"
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  before_filter :update_sanitized_params, if: :devise_controller?

  def update_sanitized_params
    devise_parameter_sanitizer.for(:sign_up) {|u| u.permit(:name, :email, :password, :password_confirmation)}
    devise_parameter_sanitizer.for(:account_update) {|u| u.permit(:name, :email, :password, :password_confirmation, :current_password)}
  end

end

app/controllers/scan_results_controller.rb
require 'hashdiff'

class ScanResultsController < ApplicationController
  def compare
    @result_a = ScanResult.find(params[:id])
    @result_b = ScanResult.find(params[:cid])

    # Make sure these ScanResults exist
    raise ActionController::RoutingError.new('Not Found') unless @result_a && @result_b

    # Ensure that user is owner of this scan
    if @result_a.scan.user != current_user or @result_b.scan.user != current_user
      head :unauthorized
    end

    # Make sure these ScanResults belong to the same Scan
    head :unauthorized unless @result_a.scan == @result_b.scan

    @results = @result_a.compare(@result_b)
  end
end

app/controllers/scans_controller.rb
class ScansController< ApplicationController
  before_filter :authenticate_user!
  before_filter :ensure_ownership, :only => [:show, :update, :rescan]

  def index
    @scans = current_user.scans.order(last_scan: :desc).limit(100)
  end

  def show
    @last_scan = @scan.scan_results.last
    @results = ScanResult.where("scan_id = ? AND raw_result IS NOT NULL", @scan.id).limit(100)
    @last_scan_with_raw = @results.last unless @results.empty?

    # Previous scans stuff
    previous_six_months = (0..6).map do |month|
      (6.months.ago + month.months).strftime("%B")
    end

    @historic_summary = { current_result: @last_scan_with_raw.id, timeline: previous_six_months, articles: @scan.get_history_of_scans(@last_scan) }

    respond_to do |format|
      format.html
      format.json { render :json => @historic_summary }
    end
  end

  def new
    @scan = Scan.new
  end

  def create
    @scan = Scan.new(scan_params)
    @scan.user = current_user
    if @scan.save
      # Schedulle the scanning job
      @scan.start_scan
      redirect_to @scan
    else
      render "new"
    end
  end

  def update
    if @scan.active
      @scan.update_attributes({active: false})
    else
      @scan.update_attributes({active: true})
    end
    redirect_to @scan
  end

  def rescan
    head :unauthorized if @scan.user != current_user
    @scan.start_scan
    redirect_to @scan
  end

  private

  def ensure_ownership
    @scan = Scan.find(params[:id])
    # Ensure that user is owner of this scan
    head :unauthorized if @scan.user != current_user
  end

  def scan_params
    params.require(:scan).permit(:targets, :frequency, :name)
  end

  def update_params
    params.require(:scan).permit(:active)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    # @users = User.all
  end

  def show
    # @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def javascript(*files)
    content_for(:scans) { javascript_include_tag(*files) }
  end
end

app/helpers/scan_results_helper.rb
module ScanResultsHelper
end

app/helpers/scans_controller_helper.rb
module ScansControllerHelper
end

app/views/home/index.html.erb
<h3>Welcome to NetDiffness</h3>

<% unless @scans %>
  <p> Please <%=link_to "Login", new_user_session_path %> to start using NetDiffness</p>
<% else %>
  <p> You have <%=link_to @scans.count, scans_path %> <%=  %> scans currently active </p>
<% end %>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li><%= link_to 'Scans', scans_path %></li>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Login', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>

app/views/layouts/_new_navigation.html.erb
<div class="col-md-3">
<div class="bs-docs-sidebar hidden-print affix-top" role="complementary">
  <ul class="nav bs-docs-sidenav">

<%# add navigation links to this file %>
<li><%= link_to 'Home', root_path %></li>
<% if user_signed_in? %>
  <li><%= link_to 'Scans', scans_path %></li>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %></li>
<% else %>

  <li><%= link_to 'Login', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<!--
  <li class="active">
  <a href="#overview">Overview</a>
  <ul class="nav">
    <li class=""><a href="#overview-doctype">HTML5 doctype</a></li>
    <li class=""><a href="#overview-mobile">Mobile first</a></li>
    <li><a href="#overview-type-links">Typography and links</a></li>
    <li class=""><a href="#overview-normalize">Normalize.css</a></li>
    <li class=""><a href="#overview-container">Containers</a></li>
  </ul>
</li>
<li>
  <a href="#grid">Grid system</a>
  <ul class="nav">
    <li><a href="#grid-intro">Introduction</a></li>
    <li><a href="#grid-media-queries">Media queries</a></li>
    <li><a href="#grid-options">Grid options</a></li>
    <li><a href="#grid-example-basic">Ex: Stacked-to-horizontal</a></li>
    <li><a href="#grid-example-fluid">Ex: Fluid container</a></li>
    <li><a href="#grid-example-mixed">Ex: Mobile and desktops</a></li>
    <li><a href="#grid-example-mixed-complete">Ex: Mobile, tablet, desktops</a></li>
    <li><a href="#grid-responsive-resets">Responsive column resets</a></li>
    <li><a href="#grid-offsetting">Offsetting columns</a></li>
    <li><a href="#grid-nesting">Nesting columns</a></li>
    <li><a href="#grid-column-ordering">Column ordering</a></li>
    <li><a href="#grid-less">Less mixins and variables</a></li>
  </ul>
</li> -->
</ul>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Netdiffness" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Netdiffness" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
<!--       <%= render 'layouts/navigation' %> -->
      <div class="bs-docs-header" id="content">
            <div class="container">
              <h1>NetDiffness</h1>
              <p>How well do you know your network perimeter?!</p>
            </div>
          </div>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= render 'layouts/new_navigation' %>

       <%= yield %>
    </main>
  </body>
<!--   <footer class="bs-docs-footer">
    <div class="container">
      <div class="bs-docs-social">
        <ul class="bs-docs-social-buttons">
          <li>
            <iframe class="github-btn" src="http://ghbtns.com/github-btn.html?user=diogomonica&amp;repo=netdiffness&amp;type=watch&amp;count=true" width="100" height="20" title="Star on GitHub"></iframe>
          </li>
          <li>
            <iframe class="github-btn" src="http://ghbtns.com/github-btn.html?user=diogomonica&amp;repo=netdiffness&amp;type=fork&amp;count=true" width="102" height="20" title="Fork on GitHub"></iframe>
          </li>
        </ul>
      </div>
      <p>Engineered by <a href="http://twitter.com/diogomonica" target="_blank">@diogomonica</a>.</p>
    </div>
  </footer> -->
</html>

app/views/scan_results/compare.html.erb
<div class="col-md-9" role="main">
  <h3>Scan Comparison</h3>

  <div class="bs-callout bs-callout-info">
    <h4>Summary of changes for <%= @result_a.scan.name %> compared with <%= ((@result_a.created_at - @result_b.created_at)/3600).round %> hours ago.</h4>
    <p>New additions appear in green and removals will show up in red</p>
  </div>
  <% if @results %>
  <div class="bs-example">
    <table class="table">
      <thead>
        <tr>
          <th>IP Address</th>
          <th>Ports</th>
        </tr>
      </thead>
      </tbody>
        <% @results.each do |change| %>

      <% if change[0] == "-" %>
        <tr class="success">
      <% else %>
        <tr class="danger">
      <% end %>
          <td><%= change[1].include?("[") ? change[1][0..-4] : change[1] %></td>
          <td><%= change[2].kind_of?(Array) ? change[2].join(',') : change[2] %></td>
        </tr>
      </tbody>
      <% end %>
    </table>
  </div>
  <% else %>
    <p>Oops, something went wrong with this comparison. Please try again.</p>
  <% end %>
  <%= link_to 'Back to Scan', @result_a.scan, :type => 'button', :class => 'btn btn-primary btn-lg' %>
</div>

app/views/scans/index.html.erb
<div class="col-md-9" role="main">
  <h3>Scan Listing</h3>
    <div class="bs-example">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Name</th>
          <th>CIDR Range</th>
          <th>Last Scanned</th>
          <th>Active</th>
        </tr>
      </thead>
      <tbody>
        <% @scans.each do |scan| %>
        <tr>
          <td><%= scan.name %></td>
          <td><code><%= link_to scan.targets, scan %></code></td>
          <td><%= scan.last_scan %></td>
          <td><%= scan.active %></td>
        <tr>
        <% end %>
      </tbody>
    </table>
  </div>
    <%= link_to 'New Scan', new_scan_path, :type => 'button', :class => 'btn btn-primary btn-lg' %>
  </div>
</div>

app/views/scans/new.html.erb
<h3>Create a new Scan</h3>
<div class="authform">
  <%= form_for @scan do |f| %>
  <div class="form-group">
    <fieldset>
      <p><b>Scan Name:</b></p>
      <%= f.text_field :name, :required => true, :autofocus => true, class: 'form-control' %><br />
    <p><b>Target Network (CIDR range):</b></p>
    <%= f.text_field :targets, :required => true, class: 'form-control' %><br />
    <p><b>Frequency (minutes):</b></p>
    <%= f.text_field :frequency, :required => true, :disabled => true, class: 'form-control' %>
  </div>
  </fieldset>
    <%= f.submit "Create Scan", :class => 'btn btn-primary btn-lg' %>
  <% end %>
</div>

app/views/scans/show.html.erb
<% javascript 'scans.js' %>
<%= yield(:scans) %>
<div class="col-md-9" role="main">
  <h3>Scan Results for <%= @scan.targets if @scan.targets %></h3>
  <div class="bs-example">
    <% if @last_scan && @last_scan.finished %>
      <table class="table table-striped">
        <thead>
          <tr>
            <th>IP Address</th>
            <th>Open Ports</th>
          </tr>
        </thead>
        <tbody>
          <% @last_scan_with_raw.result.each do |key, value| %>
          <tr>
            <td><code><%= key %></code></td>
            <td><%= value.join(', ') %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
  </div>
  <div class="highlight">
    Scanned with:
      <code><kbd>nmap -sV -oX output.xml -p 20,21,22,23,25,80,110,443,512,522,8080,1080 <%= @scan.targets %></kbd></code>
  </div>

      <h3>Compare with Previous Scans:</h3>
      <div id="history">

      </div>

<!--       <% if @results %>
        <% @results[0..-2].each do |r| %>
          <%= link_to r.created_at, controller: "scan_results", action: "compare", id: @last_scan_with_raw.id, cid: r.id %><br />
        <% end %>
      <% end %> -->

    <%= form_tag(controller: "scans", action: "rescan", method: "post") do %>
      <%= submit_tag("Rescan", :class => 'button-inline') %>
    <% end %>

    <% elsif @last_scan %>
      <p>Scan in progress... Time elapsed: <b><%= ((Time.now - @last_scan.created_at)/60).round %> minutes</b></p>
    <% else %>
      <p>Oops, this range was never scaned. Please rescan it.</p>
    <% end %>

  <%= form_for @scan, url: {action: "update"} do |f| %>
    <% if @scan.active %>
      <%= f.submit "Disable", :class => 'button-inline' %>
    <% else %>
      <%= f.submit "Enable", :class => 'button-inline' %>
    <% end %>
  <% end %>
  <br/>
</div>

app/views/users/index.html.erb
<h3>Users</h3>
<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= link_to user.email, user %> signed up <%= user.created_at.to_date %>
    </li>
  <% end %>
</ul>

app/views/users/show.html.erb
<h3>User</h3>
<p>Email: <%= @user.email if @user.email %></p>